### PR TITLE
Add support for composer 2

### PR DESCRIPTION
**Pull request by szeidler**
Adopt the Composer 2 API changes and make composer-patches-cli compatible with both version.

### CODE REVIEW

**Comment by nerdstein** [comment]
Hi there - I'd love to bump this up :+1:

**Comment by esolitos** [comment]
From my (quick) tests it seems to work as expected.

@nerdstein Can you also test that it all works as desired?

**Comment by nerdstein** [comment]
i'll be doing a test this weekend :)

**Comment by nerdstein** [comment]
My tests passed manually. SimplyTest.me is currently down because of this. I'd love to roll this in with an offer of rapid feedback so I don't have to go through and pin to composer 1 (note: this is non-trivial with the number of images I support).

**Comment by szeidler** [comment]
@nerdstein Thanks for your feedback. I will have another look into it myself and then merge and tag a release today.

**Pull request merged**
